// FR-2: Monitoring Preview (Recognition-Aware View)
// This function provides a live monitoring preview that displays annotated video frames
// generated by the background recognition engine. It operates in read-only mode and
// does NOT perform face detection, bounding box computation, or face recognition.
// The preview is intended only for observation, audit, and transparency purposes.
export const getCameraLiveDetectionStream = async (req, res) => {
  try {
    const { Camera } = await import('../models/camera.model.js');
    const camera = await Camera.findById(req.params.id);
    if (!camera) {
      return res.status(404).json({ success: false, message: 'Camera not found' });
    }

    if (!camera.isActive || camera.isUnderMaintenance) {
      return res.status(400).json({
        success: false,
        message: 'Camera is not available'
      });
    }

    // Handle local webcams
    const localWebcamTypes = ['usb_webcam', 'laptop_webcam'];
    if (localWebcamTypes.includes(camera.type)) {
      return res.status(400).json({
        success: false,
        message: 'Local webcams cannot be streamed from the server'
      });
    }

    // Check if monitoring is active for this camera
    const { getMonitoringStatus, getMonitoringResults } = await import('../services/cameraMonitoring.service.js');
    const monitoringStatus = getMonitoringStatus();
    const isMonitoringActive = monitoringStatus.data.some(m => m.cameraId === camera._id.toString());

    if (!isMonitoringActive) {
      return res.status(400).json({
        success: false,
        message: 'Camera monitoring must be active to view preview. Start monitoring first.'
      });
    }

    // Set up SSE headers for preview
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.setHeader('X-Accel-Buffering', 'no'); // Disable nginx buffering

    const frameInterval = parseInt(req.query.interval || '1000', 10); // Default 1 second
    let isActive = true;
    let lastFrameCount = -1;

    // Send initial connection message
    res.write(`data: ${JSON.stringify({
      type: 'connected',
      message: 'Monitoring preview stream started - displaying results from background recognition engine',
      cameraId: camera._id.toString(),
      cameraName: camera.name,
      isReadOnly: true // Preview is read-only, no face detection performed here
    })}\n\n`);

    // Cleanup on client disconnect
    req.on('close', () => {
      isActive = false;
      res.end();
    });

    // Stream monitoring results to preview (read-only mode)
    const streamMonitoringResults = () => {
      if (!isActive) return;

      try {
        const monitoringResult = getMonitoringResults(camera._id.toString());

        if (monitoringResult && monitoringResult.frameCount !== lastFrameCount) {
          // Send the pre-computed results from monitoring (read-only)
          // This includes:
          // - Face bounding boxes (computed in background service)
          // - Employee name or "Unknown"
          // - Match confidence score
          // - Timestamp
          // - Camera ID
          res.write(`data: ${JSON.stringify({
            type: 'frame',
            imageData: `data:image/jpeg;base64,${monitoringResult.imageData}`,
            detections: monitoringResult.detections, // Pre-computed by monitoring
            modelInfo: monitoringResult.modelInfo,
            timestamp: monitoringResult.timestamp,
            cameraId: monitoringResult.cameraId,
            frameCount: monitoringResult.frameCount,
            bestMatch: monitoringResult.bestMatch,
            isFromMonitoring: true, // Indicates this came from background monitoring
            readOnly: true // Preview does not perform detection
          })}\n\n`);

          lastFrameCount = monitoringResult.frameCount;
        }
      } catch (error) {
        console.error('Error streaming monitoring results:', error);
      }

      // Continue streaming at specified interval
      if (isActive) {
        setTimeout(streamMonitoringResults, frameInterval);
      }
    };

    // Start streaming monitoring results
    streamMonitoringResults();

  } catch (error) {
    console.error('Preview stream error:', error);
    if (!res.headersSent) {
      res.status(500).json({ success: false, message: error.message });
    }
  }
};
